import { Project } from "ts-morph";
import fs from "fs";
import path from "path";

const project = new Project({
    tsConfigFilePath: path.join(process.cwd(), "tsconfig.json"),
});

const outputDir = path.join(process.cwd(), "src", "generated", "asyncapi");
const routesPath = path.join(outputDir, "routes.ts");

interface ChannelRouteConfig {
    methodName: string;
    path: string;
    protocol: 'ws' | 'http' | 'sse';
    httpMethod: 'POST' | 'GET';
    summary?: string;
    security?: string;
    parameterCount: number;
}

interface ControllerConfig {
    name: string;
    importPath: string;
    basePath: string;
    channels: ChannelRouteConfig[];
}

async function generate() {
    console.log("🚀 Generando rutas de AsyncAPI...");

    if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
    }

    const controllers: ControllerConfig[] = [];
    const sourceFiles = project.getSourceFiles("src/modules/**/*.controller.ts");

    for (const sourceFile of sourceFiles) {
        const classes = sourceFile.getClasses();
        for (const cls of classes) {
            const asyncControllerDecorator = cls.getDecorator("AsyncAPIController");
            if (!asyncControllerDecorator) continue;

            const tsoaRouteDecorator = cls.getDecorator("Route");
            const basePath = tsoaRouteDecorator?.getArguments()[0]?.getText().replace(/['"]/g, "") || "";

            const controllerInfo: ControllerConfig = {
                name: cls.getName()!,
                importPath: './' + path.relative(outputDir, sourceFile.getFilePath()).replace(/\.ts$/, '.js').replace(/\\/g, '/'),
                basePath,
                channels: []
            };

            const methods = cls.getMethods();
            for (const method of methods) {
                const channelDec = method.getDecorator("AsyncAPIChannel");
                if (channelDec) {
                    const args = channelDec.getArguments();
                    const channelPath = args[0]?.getText().replace(/['"]/g, "") || "";

                    const optionsText = args[1]?.getText() || "{}";
                    let options: Record<string, string | undefined> = {};
                    try {
                        // eslint-disable-next-line no-eval
                        options = eval(`(${optionsText})`);
                    } catch (e) { }

                    const securityDec = method.getDecorator("Security");
                    const security = options.security || securityDec?.getArguments()[0]?.getText().replace(/['"]/g, "");

                    controllerInfo.channels.push({
                        methodName: method.getName(),
                        path: channelPath,
                        protocol: (options.protocol as 'ws' | 'http' | 'sse') || 'http',
                        httpMethod: (options.method as 'POST' | 'GET') || 'POST',
                        summary: options.summary,
                        security,
                        parameterCount: method.getParameters().length
                    });
                }
            }

            if (controllerInfo.channels.length > 0) {
                controllers.push(controllerInfo);
            }
        }
    }

    let content = `/* tslint:disable */
/* eslint-disable */
// WARNING: This file was auto-generated by flAIghts. Please do not modify it.
import { Router, type Response, type Request, type NextFunction } from 'express';
import { WebSocket } from 'ws';
import { container } from 'tsyringe';
import { expressAuthentication } from '../../modules/auth/authentication.js';
import type { AuthenticatedUser } from '../../modules/auth/auth.types.js';
import { wrapWebSocket } from '../../utils/asyncapi.utils.js';

${controllers.map(c => `import { ${c.name} } from '${c.importPath}';`).join('\n')}

// ==================== TIPOS DE PETICIÓN ====================
declare module 'express-serve-static-core' {
    interface Request {
        /**
         * Propiedad user inyectada mediante autenticación.
         */
        user: AuthenticatedUser | null;
    }
    interface Response {
        flush?: () => void;
    }
    interface Router {
        ws?: (path: string, ...middlewares: Array<(ws: WebSocket, req: Request, next: NextFunction) => void>) => Router;
    }
}

declare module 'ws' {
    interface WebSocket {
        /**
         * Método inyectado automáticamente para soportar tipado bidireccional.
         */
        onMessage: (cb: (data: unknown) => void) => void;
    }
}

interface AuthenticatedRequest extends Request {
    user: AuthenticatedUser;
}

interface OptionalRequest extends Request {
    user: AuthenticatedUser | null;
}

interface PublicRequest extends Request {
    user: null;
}
// ========================================================

/**
 * Type Guard para identificar generadores asíncronos.
 */
function isAsyncGenerator(obj: unknown): obj is AsyncGenerator<unknown, unknown, unknown> {
    return !!obj && typeof obj === 'object' && Symbol.asyncIterator in obj;
}

export function RegisterAsyncRoutes(app: Router) {
${controllers.map(c => {
        return c.channels.map((chan) => {
            const fullPath = ('/' + c.basePath + '/' + chan.path).replace(/\/+/g, '/');
            const isWS = chan.protocol === 'ws';

            const authLogic = chan.security ? (isWS ? `
    async (ws: WebSocket, req: Request, next: NextFunction) => {
        try {
            const user = await expressAuthentication(req, "${chan.security}");
            req.user = user;
            next();
        } catch (err) {
            ws.terminate();
        }
    },` : `
    async (req: Request, res: Response, next: NextFunction) => {
        try {
            const user = await expressAuthentication(req, "${chan.security}");
            req.user = user;
            next();
        } catch (err) {
            res.status(401).json({ status: 'fail', data: { message: 'Unauthorized' } });
        }
    },`) : "";

            let reqType = 'PublicRequest';
            if (chan.security === 'jwt') reqType = 'AuthenticatedRequest';
            if (chan.security === 'jwt-optional') reqType = 'OptionalRequest';

            if (isWS) {
                const possibleArgs = ['typedWs', 'reqWithUser.user', 'reqWithUser'];
                const callArgs = possibleArgs.slice(0, chan.parameterCount).join(', ');

                return `    // Canal WebSocket para ${chan.methodName}
    if (app.ws) {
        app.ws('${fullPath}', ${authLogic}
            async (ws: WebSocket, req: Request) => {
                try {
                    const reqWithUser = req as unknown as ${reqType};
                    const typedWs = wrapWebSocket(ws);

                    const controller = container.resolve(${c.name});
                    // @ts-ignore
                    await controller.${chan.methodName}(${callArgs});
                } catch (err) {
                    ws.close(1011, 'Internal Server Error');
                }
            }
        );
    } else {
        console.warn('⚠️ Se intentó registrar una ruta WebSocket (${fullPath}) pero express-ws no está configurado.');
    }`;
            } else {
                const possibleArgs = ['reqWithUser.body', 'reqWithUser.user', 'reqWithUser', 'res'];
                const callArgs = possibleArgs.slice(0, chan.parameterCount).join(', ');

                return `    // Canal SSE para ${chan.methodName}
    app.${chan.httpMethod.toLowerCase()}('${fullPath}', ${authLogic}
        async (req: Request, res: Response, next: NextFunction) => {
            try {
                const reqWithUser = req as unknown as ${reqType};
                const controller = container.resolve(${c.name});
                // @ts-ignore
                const result = await controller.${chan.methodName}(${callArgs});
                
                if (isAsyncGenerator(result)) {
                    await streamToSSE(result, res);
                } else if (!res.headersSent) {
                    res.json(result);
                }
            } catch (err) {
                next(err);
            }
        }
    );`;
            }
        }).join('\n');
    }).join('\n')}
}

/**
 * Envia eventos de un AsyncGenerator como Server-Sent Events (SSE).
 */
async function streamToSSE<T>(generator: AsyncGenerator<T, unknown, unknown>, res: Response) {
    if (res.flush) res.flush();

    let isClosed = false;
    res.on('close', () => {
        isClosed = true;
        // Notificamos al generador que debe terminar para liberar recursos en el backend
        generator.return(null).catch(err => console.error('[SSE] Error closing generator:', err));
    });

    try {
        for await (const event of generator) {
            if (isClosed) break;
            res.write(\`data: \${JSON.stringify(event)}\\n\\n\`);
            if (res.flush) res.flush();
        }
    } catch (error: unknown) {
        if (!isClosed) {
            const errorMsg = error instanceof Error ? error.message : 'Unknown error';
            res.write(\`data: \${JSON.stringify({ type: 'error', message: errorMsg })}\\n\\n\`);
            if (res.flush) res.flush();
        }
    } finally {
        if (!res.writableEnded) {
            res.end();
        }
    }
}
`;

    fs.writeFileSync(routesPath, content);
    console.log(`✨ Rutas de AsyncAPI generadas.`);
}

generate().catch(console.error);
