import fs from 'fs';
import path from 'path';
import { Project, InterfaceDeclaration, TypeAliasDeclaration } from 'ts-morph';

/**
 * Script to post-process openapi.json generated by TSOA.
 * It adds an 'enum' of possible error messages to the 'message' field in ValidationDetails schemas.
 * This script uses recursive type traversal to handle nested properties and follows
 * official TSOA error message templates.
 */

const WORK_DIR = process.cwd();
const OPENAPI_PATH = path.join(WORK_DIR, 'build', 'openapi.json');

if (!fs.existsSync(OPENAPI_PATH)) {
    console.error(`OpenAPI file not found at ${OPENAPI_PATH}`);
    process.exit(1);
}

const openapi = JSON.parse(fs.readFileSync(OPENAPI_PATH, 'utf-8'));

const project = new Project({
    tsConfigFilePath: path.join(WORK_DIR, 'tsconfig.json'),
});

console.log('Post-processing OpenAPI spec with official TSOA error messages (Recursive Mode)...');

/**
 * Maps a validator tag to its official TSOA error message.
 * Supports custom messages if provided in JSDoc.
 */
function getTsoaErrorMessage(tagName: string, tagValue?: string, propertyName?: string, customMsg?: string, enumValues?: string[]): string {
    if (customMsg) return customMsg;

    switch (tagName) {
        case 'minLength': return `minLength ${tagValue}`;
        case 'maxLength': return `maxLength ${tagValue}`;
        case 'pattern': return `Not match in '${tagValue}'`;
        case 'minimum': return `min ${tagValue}`;
        case 'maximum': return `max ${tagValue}`;
        case 'minDate': return `minDate '${tagValue}'`;
        case 'maxDate': return `maxDate '${tagValue}'`;
        case 'minItems': return `minItems ${tagValue}`;
        case 'maxItems': return `maxItems ${tagValue}`;
        case 'uniqueItems': return `required unique array`;
        case 'required': return `'${propertyName}' is required`;
        case 'format':
            if (tagValue === 'date') return 'invalid ISO 8601 date format, i.e. YYYY-MM-DD';
            if (tagValue === 'datetime') return 'invalid ISO 8601 datetime format, i.e. YYYY-MM-DDTHH:mm:ss';
            return `invalid ${tagValue} format`;
        case 'isString': return 'invalid string value';
        case 'isNumber': return 'invalid float number';
        case 'isInt': case 'isLong': return 'invalid integer number';
        case 'isFloat': case 'isDouble': return 'invalid float number';
        case 'isBool': case 'isBoolean': return 'invalid boolean value';
        case 'isArray': return 'invalid array';
        case 'enum':
            if (enumValues && enumValues.length > 0) {
                return `should be one of the following; [${enumValues.join(',')}]`;
            }
            return 'invalid enum value';
        default: return tagValue ? `${tagName} ${tagValue}` : tagName;
    }
}

/**
 * Finds a declaration by name across all source files.
 */
function findDeclaration(name: string) {
    for (const sf of project.getSourceFiles()) {
        const decl = sf.getInterface(name) || sf.getTypeAlias(name) || sf.getEnum(name);
        if (decl) return decl;
    }
    return null;
}

/**
 * Recursively extracts validation messages for a specific property path.
 */
function getMessagesForPath(rootTypeName: string, pathParts: string[]): string[] {
    let currentDecl: any = findDeclaration(rootTypeName);
    let messages: string[] = [];

    // Current property we are looking at in the traversal
    let currentProp: any = null;

    for (let i = 0; i < pathParts.length; i++) {
        const part = pathParts[i];

        if (!currentDecl) return [];

        // Try to find the property in the current declaration
        let prop: any = null;
        if (InterfaceDeclaration.isInterfaceDeclaration(currentDecl)) {
            prop = currentDecl.getProperty(part);
        } else if (TypeAliasDeclaration.isTypeAliasDeclaration(currentDecl)) {
            const typeNode = currentDecl.getTypeNode();
            if (typeNode) {
                const typeLiteral = (typeNode as any).asKind?.(188 /* TypeLiteral */);
                if (typeLiteral) {
                    prop = typeLiteral.getProperty(part);
                }
            }
        }

        if (!prop) {
            // Check if it's an array indexing part (e.g. "items[0]")
            const arrayMatch = part.match(/^(\w+)\[\d+\]$/);
            if (arrayMatch) {
                const arrayPropName = arrayMatch[1];
                const arrayProp = (currentDecl as any).getProperty?.(arrayPropName);
                if (arrayProp) {
                    const arrayType = arrayProp.getType();
                    const itemType = arrayType.getArrayElementType();
                    if (itemType) {
                        const nextTypeName = itemType.getSymbol()?.getName();
                        if (nextTypeName) {
                            currentDecl = findDeclaration(nextTypeName);
                            continue;
                        }
                    }
                }
            }
            return []; // Path broken
        }

        currentProp = prop;

        // If not the last part, keep traversing
        if (i < pathParts.length - 1) {
            const propType = prop.getType();
            const nextTypeName = propType.getSymbol()?.getName() || propType.getText();
            currentDecl = findDeclaration(nextTypeName);
        }
    }

    if (currentProp) {
        const propName = currentProp.getName();

        // Add required if applicable
        if (!currentProp.hasQuestionToken()) {
            messages.push(getTsoaErrorMessage('required', undefined, propName));
        }

        // Add type-based defaults
        const type = currentProp.getType();
        if (type.isString()) messages.push(getTsoaErrorMessage('isString'));
        else if (type.isNumber()) messages.push(getTsoaErrorMessage('isNumber'));
        else if (type.isBoolean()) messages.push(getTsoaErrorMessage('isBool'));
        else if (type.isArray()) messages.push(getTsoaErrorMessage('isArray'));

        // Add JSDoc validators
        const docs = currentProp.getJsDocs();
        for (const doc of docs) {
            for (const tag of doc.getTags()) {
                const tagName = tag.getTagName();
                const comment = tag.getComment();
                const commentText = Array.isArray(comment)
                    ? comment.map((c: any) => c.getText ? c.getText() : c.text || '').join(' ')
                    : (comment as string) || '';

                const parts = commentText.trim().split(/\s+/);
                const firstPart = parts[0];
                const restOfMsg = parts.slice(1).join(' ');

                const tsoaValidators = [
                    'minLength', 'maxLength', 'pattern', 'format',
                    'minimum', 'maximum', 'minDate', 'maxDate',
                    'enum', 'isInt', 'isFloat', 'isLong', 'isDouble',
                    'minItems', 'maxItems', 'uniqueItems', 'isString', 'isBoolean', 'isDate', 'isDateTime'
                ];

                if (tsoaValidators.includes(tagName)) {
                    let enumValues: string[] = [];
                    let tagValue = firstPart;
                    let customMsg = restOfMsg;

                    if (tagName === 'enum') {
                        if (type.isUnion()) {
                            enumValues = type.getUnionTypes().map(t => t.getText().replace(/['"]/g, ''));
                        } else {
                            enumValues = parts.map(v => v.replace(/['"]/g, ''));
                            tagValue = parts.join(' ');
                            customMsg = '';
                        }
                    }
                    messages.push(getTsoaErrorMessage(tagName, tagValue, propName, customMsg, enumValues));
                }
            }
        }
    }

    return Array.from(new Set(messages));
}

// Iterate over schemas
const schemas = openapi.components.schemas;
let count = 0;

for (const [schemaName, schema] of Object.entries(schemas)) {
    const match = schemaName.match(/^ValidationDetails_(\w+)Path_(\w+)__/);
    if (!match) continue;

    const location = match[1].toLowerCase();
    const interfaceName = match[2];
    const properties = (schema as any).properties;

    if (!properties) continue;

    for (const [propPath, propSchema] of Object.entries(properties)) {
        // propPath is "body.user.email"
        const parts = propPath.split('.');
        const pathAfterPrefix = parts.slice(1); // skip "body"

        let possibleMessages: string[] = [];

        if (pathAfterPrefix.length === 0) {
            // Root validation (e.g. the whole body)
            possibleMessages = [getTsoaErrorMessage('required', undefined, location), 'invalid object'];
        } else {
            possibleMessages = getMessagesForPath(interfaceName, pathAfterPrefix);
        }

        if (possibleMessages.length > 0 && (propSchema as any).properties && (propSchema as any).properties.message) {
            (propSchema as any).properties.message.enum = possibleMessages;
            count++;
        }
    }
}

console.log(`Updated ${count} validation error messages with official TSOA strings (Recursive Mode).`);

fs.writeFileSync(OPENAPI_PATH, JSON.stringify(openapi, null, 2));
fs.writeFileSync(OPENAPI_PATH, JSON.stringify(openapi, null, 2));
