export const COUNTRY_NAMES: Record<string, string[]> = {
    "AF": ["Afghanistan", "Afganistán"],
    "AX": ["Åland Islands", "Islas Åland"],
    "AL": ["Albania", "Albania"],
    "DZ": ["Algeria", "Argelia"],
    "AS": ["American Samoa", "Samoa Americana"],
    "AD": ["Andorra", "Andorra"],
    "AO": ["Angola", "Angola"],
    "AI": ["Anguilla", "Anguila"],
    "AQ": ["Antarctica", "Antártida"],
    "AG": ["Antigua & Barbuda", "Antigua y Barbuda"],
    "AR": ["Argentina", "Argentina"],
    "AM": ["Armenia", "Armenia"],
    "AW": ["Aruba", "Aruba"],
    "AU": ["Australia", "Australia"],
    "AT": ["Austria", "Austria"],
    "AZ": ["Azerbaijan", "Azerbaiyán"],
    "BS": ["Bahamas", "Bahamas"],
    "BH": ["Bahrain", "Baréin"],
    "BD": ["Bangladesh", "Bangladés"],
    "BB": ["Barbados", "Barbados"],
    "BY": ["Belarus", "Bielorrusia"],
    "BE": ["Belgium", "Bélgica"],
    "BZ": ["Belize", "Belice"],
    "BJ": ["Benin", "Benín"],
    "BM": ["Bermuda", "Bermudas"],
    "BT": ["Bhutan", "Bután"],
    "BO": ["Bolivia", "Bolivia"],
    "BA": ["Bosnia & Herzegovina", "Bosnia y Herzegovina"],
    "BW": ["Botswana", "Botsuana"],
    "BV": ["Bouvet Island", "Isla Bouvet"],
    "BR": ["Brazil", "Brasil"],
    "IO": ["British Indian Ocean Territory", "Territorio Británico del Océano Índico"],
    "VG": ["British Virgin Islands", "Islas Vírgenes Británicas"],
    "BN": ["Brunei", "Brunéi"],
    "BG": ["Bulgaria", "Bulgaria"],
    "BF": ["Burkina Faso", "Burkina Faso"],
    "BI": ["Burundi", "Burundi"],
    "KH": ["Cambodia", "Camboya"],
    "CM": ["Cameroon", "Camerún"],
    "CA": ["Canada", "Canadá"],
    "CV": ["Cape Verde", "Cabo Verde"],
    "BQ": ["Caribbean Netherlands", "Caribe neerlandés"],
    "KY": ["Cayman Islands", "Islas Caimán"],
    "CF": ["Central African Republic", "República Centroafricana"],
    "TD": ["Chad", "Chad"],
    "CL": ["Chile", "Chile"],
    "CN": ["China", "China"],
    "CX": ["Christmas Island", "Isla de Navidad"],
    "CC": ["Cocos (Keeling) Islands", "Islas Cocos"],
    "CO": ["Colombia", "Colombia"],
    "KM": ["Comoros", "Comoras"],
    "CG": ["Congo - Brazzaville", "Congo"],
    "CD": ["Congo - Kinshasa", "República Democrática del Congo"],
    "CK": ["Cook Islands", "Islas Cook"],
    "CR": ["Costa Rica", "Costa Rica"],
    "CI": ["Côte d’Ivoire", "Côte d’Ivoire"],
    "HR": ["Croatia", "Croacia"],
    "CU": ["Cuba", "Cuba"],
    "CW": ["Curaçao", "Curazao"],
    "CY": ["Cyprus", "Chipre"],
    "CZ": ["Czechia", "Chequia"],
    "DK": ["Denmark", "Dinamarca"],
    "DJ": ["Djibouti", "Yibuti"],
    "DM": ["Dominica", "Dominica"],
    "DO": ["Dominican Republic", "República Dominicana"],
    "EC": ["Ecuador", "Ecuador"],
    "EG": ["Egypt", "Egipto"],
    "SV": ["El Salvador", "El Salvador"],
    "GQ": ["Equatorial Guinea", "Guinea Ecuatorial"],
    "ER": ["Eritrea", "Eritrea"],
    "EE": ["Estonia", "Estonia"],
    "SZ": ["Eswatini", "Esuatini"],
    "ET": ["Ethiopia", "Etiopía"],
    "FK": ["Falkland Islands", "Islas Malvinas"],
    "FO": ["Faroe Islands", "Islas Feroe"],
    "FJ": ["Fiji", "Fiyi"],
    "FI": ["Finland", "Finlandia"],
    "FR": ["France", "Francia"],
    "GF": ["French Guiana", "Guayana Francesa"],
    "PF": ["French Polynesia", "Polinesia Francesa"],
    "TF": ["French Southern Territories", "Territorios Australes Franceses"],
    "GA": ["Gabon", "Gabón"],
    "GM": ["Gambia", "Gambia"],
    "GE": ["Georgia", "Georgia"],
    "DE": ["Germany", "Alemania"],
    "GH": ["Ghana", "Ghana"],
    "GI": ["Gibraltar", "Gibraltar"],
    "GR": ["Greece", "Grecia"],
    "GL": ["Greenland", "Groenlandia"],
    "GD": ["Grenada", "Granada"],
    "GP": ["Guadeloupe", "Guadalupe"],
    "GU": ["Guam", "Guam"],
    "GT": ["Guatemala", "Guatemala"],
    "GG": ["Guernsey", "Guernsey"],
    "GN": ["Guinea", "Guinea"],
    "GW": ["Guinea-Bissau", "Guinea-Bisáu"],
    "GY": ["Guyana", "Guyana"],
    "HT": ["Haiti", "Haití"],
    "HM": ["Heard & McDonald Islands", "Islas Heard y McDonald"],
    "HN": ["Honduras", "Honduras"],
    "HK": ["Hong Kong SAR China", "RAE de Hong Kong (China)"],
    "HU": ["Hungary", "Hungría"],
    "IS": ["Iceland", "Islandia"],
    "IN": ["India", "India"],
    "ID": ["Indonesia", "Indonesia"],
    "IR": ["Iran", "Irán"],
    "IQ": ["Iraq", "Irak"],
    "IE": ["Ireland", "Irlanda"],
    "IM": ["Isle of Man", "Isla de Man"],
    "IL": ["Israel", "Israel"],
    "IT": ["Italy", "Italia"],
    "JM": ["Jamaica", "Jamaica"],
    "JP": ["Japan", "Japón"],
    "JE": ["Jersey", "Jersey"],
    "JO": ["Jordan", "Jordania"],
    "KZ": ["Kazakhstan", "Kazajistán"],
    "KE": ["Kenya", "Kenia"],
    "KI": ["Kiribati", "Kiribati"],
    "KW": ["Kuwait", "Kuwait"],
    "KG": ["Kyrgyzstan", "Kirguistán"],
    "LA": ["Laos", "Laos"],
    "LV": ["Latvia", "Letonia"],
    "LB": ["Lebanon", "Líbano"],
    "LS": ["Lesotho", "Lesoto"],
    "LR": ["Liberia", "Liberia"],
    "LY": ["Libya", "Libia"],
    "LI": ["Liechtenstein", "Liechtenstein"],
    "LT": ["Lithuania", "Lituania"],
    "LU": ["Luxembourg", "Luxemburgo"],
    "MO": ["Macao SAR China", "RAE de Macao (China)"],
    "MG": ["Madagascar", "Madagascar"],
    "MW": ["Malawi", "Malaui"],
    "MY": ["Malaysia", "Malasia"],
    "MV": ["Maldives", "Maldivas"],
    "ML": ["Mali", "Mali"],
    "MT": ["Malta", "Malta"],
    "MH": ["Marshall Islands", "Islas Marshall"],
    "MQ": ["Martinique", "Martinica"],
    "MR": ["Mauritania", "Mauritania"],
    "MU": ["Mauritius", "Mauricio"],
    "YT": ["Mayotte", "Mayotte"],
    "MX": ["Mexico", "México"],
    "FM": ["Micronesia", "Micronesia"],
    "MD": ["Moldova", "Moldavia"],
    "MC": ["Monaco", "Mónaco"],
    "MN": ["Mongolia", "Mongolia"],
    "ME": ["Montenegro", "Montenegro"],
    "MS": ["Montserrat", "Montserrat"],
    "MA": ["Morocco", "Marruecos"],
    "MZ": ["Mozambique", "Mozambique"],
    "MM": ["Myanmar (Burma)", "Myanmar (Birmania)"],
    "NA": ["Namibia", "Namibia"],
    "NR": ["Nauru", "Nauru"],
    "NP": ["Nepal", "Nepal"],
    "NL": ["Netherlands", "Países Bajos"],
    "NC": ["New Caledonia", "Nueva Caledonia"],
    "NZ": ["New Zealand", "Nueva Zelanda"],
    "NI": ["Nicaragua", "Nicaragua"],
    "NE": ["Niger", "Níger"],
    "NG": ["Nigeria", "Nigeria"],
    "NU": ["Niue", "Niue"],
    "NF": ["Norfolk Island", "Isla Norfolk"],
    "KP": ["North Korea", "Corea del Norte"],
    "MK": ["North Macedonia", "Macedonia del Norte"],
    "MP": ["Northern Mariana Islands", "Islas Marianas del Norte"],
    "NO": ["Norway", "Noruega"],
    "OM": ["Oman", "Omán"],
    "PK": ["Pakistan", "Pakistán"],
    "PW": ["Palau", "Palaos"],
    "PS": ["Palestinian Territories", "Territorios Palestinos"],
    "PA": ["Panama", "Panamá"],
    "PG": ["Papua New Guinea", "Papúa Nueva Guinea"],
    "PY": ["Paraguay", "Paraguay"],
    "PE": ["Peru", "Perú"],
    "PH": ["Philippines", "Filipinas"],
    "PN": ["Pitcairn Islands", "Islas Pitcairn"],
    "PL": ["Poland", "Polonia"],
    "PT": ["Portugal", "Portugal"],
    "PR": ["Puerto Rico", "Puerto Rico"],
    "QA": ["Qatar", "Catar"],
    "RE": ["Réunion", "Reunión"],
    "RO": ["Romania", "Rumanía"],
    "RU": ["Russia", "Rusia"],
    "RW": ["Rwanda", "Ruanda"],
    "WS": ["Samoa", "Samoa"],
    "SM": ["San Marino", "San Marino"],
    "ST": ["São Tomé & Príncipe", "Santo Tomé y Príncipe"],
    "SA": ["Saudi Arabia", "Arabia Saudí"],
    "SN": ["Senegal", "Senegal"],
    "RS": ["Serbia", "Serbia"],
    "SC": ["Seychelles", "Seychelles"],
    "SL": ["Sierra Leone", "Sierra Leone"],
    "SG": ["Singapore", "Singapur"],
    "SX": ["Sint Maarten", "Sint Maarten"],
    "SK": ["Slovakia", "Eslovaquia"],
    "SI": ["Slovenia", "Eslovenia"],
    "SB": ["Solomon Islands", "Islas Salomón"],
    "SO": ["Somalia", "Somalia"],
    "ZA": ["South Africa", "Sudáfrica"],
    "GS": ["South Georgia & South Sandwich Islands", "Islas Georgia del Sur y Sandwich del Sur"],
    "KR": ["South Korea", "Corea del Sur"],
    "SS": ["South Sudan", "Sudán del Sur"],
    "ES": ["Spain", "España"],
    "LK": ["Sri Lanka", "Sri Lanka"],
    "BL": ["St. Barthélemy", "San Bartolomé"],
    "SH": ["St. Helena", "Santa Elena"],
    "KN": ["St. Kitts & Nevis", "San Cristóbal y Nieves"],
    "LC": ["St. Lucia", "Santa Lucía"],
    "MF": ["St. Martin", "San Martín"],
    "PM": ["St. Pierre & Miquelon", "San Pedro y Miquelón"],
    "VC": ["St. Vincent & Grenadines", "San Vicente y las Granadinas"],
    "SD": ["Sudan", "Sudán"],
    "SR": ["Suriname", "Surinam"],
    "SJ": ["Svalbard & Jan Mayen", "Svalbard y Jan Mayen"],
    "SE": ["Sweden", "Suecia"],
    "CH": ["Switzerland", "Suiza"],
    "SY": ["Syria", "Siria"],
    "TW": ["Taiwan", "Taiwán"],
    "TJ": ["Tajikistan", "Tayikistán"],
    "TZ": ["Tanzania", "Tanzania"],
    "TH": ["Thailand", "Tailandia"],
    "TL": ["Timor-Leste", "Timor-Leste"],
    "TG": ["Togo", "Togo"],
    "TK": ["Tokelau", "Tokelau"],
    "TO": ["Tonga", "Tonga"],
    "TT": ["Trinidad & Tobago", "Trinidad y Tobago"],
    "TN": ["Tunisia", "Túnez"],
    "TR": ["Turkey", "Turquía"],
    "TM": ["Turkmenistan", "Turkmenistán"],
    "TC": ["Turks & Caicos Islands", "Islas Turcas y Caicos"],
    "TV": ["Tuvalu", "Tuvalu"],
    "UM": ["U.S. Outlying Islands", "Islas menores alejadas de EE. UU."],
    "VI": ["U.S. Virgin Islands", "Islas Vírgenes de EE. UU."],
    "UG": ["Uganda", "Uganda"],
    "UA": ["Ukraine", "Ucrania"],
    "AE": ["United Arab Emirates", "Emiratos Árabes Unidos"],
    "GB": ["United Kingdom", "Reino Unido"],
    "US": ["United States", "Estados Unidos"],
    "UY": ["Uruguay", "Uruguay"],
    "UZ": ["Uzbekistan", "Uzbekistán"],
    "VU": ["Vanuatu", "Vanuatu"],
    "VA": ["Vatican City", "Ciudad del Vaticano"],
    "VE": ["Venezuela", "Venezuela"],
    "VN": ["Vietnam", "Vietnam"],
    "WF": ["Wallis & Futuna", "Wallis y Futuna"],
    "EH": ["Western Sahara", "Sáhara Occidental"],
    "YE": ["Yemen", "Yemen"],
    "ZM": ["Zambia", "Zambia"],
    "ZW": ["Zimbabwe", "Zimbabue"]
};
